# Generated by Django 5.1.4 on 2025-01-13 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='places_visited',
        ),
        migrations.AlterField(
            model_name='placevisited',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_visited', to='trip.trip'),
        ),
    ]
