# Generated by Django 5.1.4 on 2025-01-29 17:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trip', '0002_remove_trip_places_visited_alter_placevisited_trip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='modeoftransport',
            options={'verbose_name': 'Mode of Transport', 'verbose_name_plural': 'Mode of Transport'},
        ),
        migrations.AlterModelOptions(
            name='placevisited',
            options={'verbose_name': 'Place Visited', 'verbose_name_plural': 'Places Visited'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AddField(
            model_name='modeoftransport',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trip.trip', verbose_name='Trip'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rooms_booked',
            field=models.PositiveIntegerField(verbose_name='Rooms Booked'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='trip.trip', verbose_name='Trip'),
        ),
        migrations.AlterField(
            model_name='media',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='media',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media_uploads/', verbose_name='Media File'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=5, verbose_name='Media Type'),
        ),
        migrations.AlterField(
            model_name='media',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='modeoftransport',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='modeoftransport',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='modeoftransport',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='modeoftransport',
            name='mode',
            field=models.CharField(choices=[('Car', 'Car'), ('Bus', 'Bus'), ('Train', 'Train'), ('Flight', 'Flight'), ('Walking', 'Walking'), ('Bicycle', 'Bicycle'), ('Boat', 'Boat'), ('Other', 'Other')], max_length=20, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='modeoftransport',
            name='places_visited',
            field=models.ManyToManyField(blank=True, related_name='visited_by_transport', to='trip.placevisited', verbose_name='Places Visited'),
        ),
        migrations.AlterField(
            model_name='modeoftransport',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='trip.trip', verbose_name='Trip'),
        ),
        migrations.AlterField(
            model_name='placevisited',
            name='best_time_to_visit',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=50, null=True, verbose_name='Best Time to Visit'),
        ),
        migrations.AlterField(
            model_name='placevisited',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='placevisited',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='placevisited',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='places_visited/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='placevisited',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='placevisited',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='placevisited',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_visited', to='trip.trip', verbose_name='Trip'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=100, verbose_name='Meal Type'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='trip.trip', verbose_name='Trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='best_time_to_visit',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Autumn', 'Autumn')], max_length=100, null=True, verbose_name='Best Time to Visit'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='currency_used',
            field=models.CharField(max_length=255, verbose_name='Currency Used'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='days',
            field=models.PositiveIntegerField(default=0, verbose_name='Days'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='emergency_numbers',
            field=models.CharField(max_length=255, verbose_name='Emergency Numbers'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image_cover',
            field=models.ImageField(upload_to='trips/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='language_spoken',
            field=models.CharField(blank=True, max_length=255, verbose_name='Language Spoken'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='nights',
            field=models.PositiveIntegerField(default=0, verbose_name='Nights'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of People'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='starting_location',
            field=models.CharField(max_length=255, verbose_name='Starting Location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
