# Generated by Django 5.1.4 on 2025-02-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_activity_best_time_to_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
