# Generated by Django 5.1.4 on 2025-02-17 18:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_trip_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location'),
        ),
    ]
