# Generated by Django 5.1.4 on 2025-02-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_remove_activity_coordinates_remove_hotel_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('1 ', 'india'), ('2', 'usa'), ('3', 'saudi arabia')])),
            ],
        ),
    ]
