# Generated by Django 5.1.4 on 2025-04-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0012_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
    ]
