# Generated by Django 5.1.4 on 2025-07-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0013_delete_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='best_time_to_visit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Best Time to Visit'),
        ),
        migrations.AlterField(
            model_name='placevisited',
            name='best_time_to_visit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Best Time to Visit'),
        ),
    ]
