# Generated by Django 5.1.4 on 2025-07-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_alter_activity_best_time_to_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='meal_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meal Type'),
        ),
    ]
